### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by zziemke** [kevincon/utilityknife#1]
Hi,
may I ask if this is still working? :)

**Comment by kevincon** [comment]
Hey @zziemke, it was not working due to how outdated the versions of the `rq`, `Flask`, and `dropbox` Python packages it was targeting were (e.g. the server the `dropbox` package was trying to hit was no longer correct) , but I updated `requirements.txt` to use the latest version of those packages and updated the app to use all the new versions of the relevant APIs and now the app works for me™. I didn't spend much time making it very robust to errors, though, so I'm sure it's not bullet-proof. I also added some more details to the README for how to set it up, so if you follow those instructions you should also be able to use it.
